# -*- coding: utf-8 -*-
"""Project 3- Python Rock, Paper Scissor game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7kmreXXCfkR-_TfZuu-_wL1-BwLTzI1
"""

import random

human_win=0
computer_win=0

options=["rock","paper","scissors"]

while True:

    human_input=input("Type Rock/Paper/Scissors or Q to quit: ").lower()

    if human_input == "q":
        break

    if human_input not in options:
        continue

    random_number=random.randint(0,2)
    #0:Rock, 1:Paper, 2:Scissors
    computer_pick=options[random_number]

    print("computer picked " + computer_pick +".")

    if human_input=="rock" and computer_pick=="Scissors":
       print("You won!!!")
       human_win+=1

    elif human_input=="paper" and computer_pick=="rock":
        print("You won!!!")
        human_win+=1

    elif human_input=="scissors" and computer_pick=="paper":
        print("You won!!!")
        human_win+=1

    else:
        print("You lost!!!")
        computer_win+=1

print("You win ", human_win,".")
print("Computer wins ", computer_win,".")

print("Thank you for playing!!!")