# -*- coding: utf-8 -*-
"""Project 2- Python Number Guessing Game .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZeHyHUf6b9hVi-9H442YWhnvOBMhAm1C
"""

import random

max_number=input("Type any number: ")

if max_number.isdigit():
  max_number=int(max_number)

  if max_number<=0:
    print("Please enter number >0")
    quit()

else:
  print("Please type a number next time")

random_number=random.randint(0,max_number)
#print(random_number)

guess=0

while True:
  guess+=1
  take_a_guess=input("Enter any number: ")
  if take_a_guess.isdigit():
    take_a_guess=int(take_a_guess)
  else:
    print("Please enter number in next attempt")
    continue

  if take_a_guess==random_number:
    print("Your prediction is correct!!!")
    break
  elif take_a_guess>random_number:
    print("Think about number less than that....: )")
  else:
    print("Think bigggg!!!")

print("You have predicted correct number in ", guess, "guesses")

#decide whether you are good at guessing number game.....
if guess < (random_number/2):
  print("Good job!!!")
else:
  print("Better luck next time!!!!")