# -*- coding: utf-8 -*-
"""Python - Dictionary .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7Cvufye04c4GrJunW4McTkse9XHp9Ue

**Dictionary**


--> Python dictionary is a container of the unordered set of objects like lists. The object are surrounded by
 { }

-->The items in a dictionary are a comma - separated list of key value pairs, where keys and value are python  data types.

-->Each object or value accessed by key and keys are unique in the dictionary.

--> As keys are used for indexing, they must be the immutable type(string, number tuple)

--> we can create empty dictionary { }.

**Create a dictionary**
"""

color= {"col 1":'red', 'col 2':'green'}
print(color)

"""** Get a value by key in Python dictionary**"""

dict={1:20.5, 2:30.3,3:23,4:33}
print(dict)

#access value using key
print(dict[1])

print(dict[3])

#Accessing value using get() method
dict.get(1)

dict.get(2)

"""**Add key/value to a dictionary in Python**"""

dic={'pdy1' : 'Dictionary'}

dic['pdy2']='string'
print(dic)

#Using update() method to add key value pairs into dictionary

dic1={0:10,1:10}

dic1.update({2:30})
print(dic1)

"""**Iterate over Python dictionaries using for loops**"""

dict1={'red':1,'green':2,'blue':3}

for color_key,value in dict1.items():
  print(color_key,"corresponds to",value)

"""**remove a key from python dictionary**"""

dict1={'a':1,'b':2,'c':3}
print(dict1)

if 'a' in dict1:
  del dict1['a']

print(dict1)

"""**test whether a python dictionary contains a speicific key**"""

fruits={}

fruits['apple']=1
fruits['mango']=2

print(fruits)

#use in

if 'mango' in fruits:
  print("has mango")
else:
  print("no mango")

if 'orange' in fruits:
  print("has orange")
else:
  print("no orange")